baseURL: https://gyulakerezsi.ro/
languageCode: en-us
title: Gyula's blog
theme: hugo-bootswatch-slate
author: Gyula Kerezsi
copyright: "&copy; 2017-2021. All rights reserved."
canonifyurls: true
paginate: 10

params:
  # Shown in the home page
  subtitle: and stuff
  brand: Gyula's blog
  # CSS name for highlight.js
  highlightjs: vs2015
  highlightjs_extra_languages:
    - yaml
    - javascript
    - xml
    - css
    - cs
    - bash
    - ini
  
  dateFormat: 2006-01-02 15:04
  custom_css: 
    - /css/site-override.css
  custom_js: []

social:
  twitter: gradientByte
  github: gardient
  gitlab: gardient
  deviantart: gradientByte

permalinks:
  post: /:year/:month/:title/

menu:
  # Shown in the side menu.
  main:
    - name: Posts
      pre: <i class='fa fa-list fa-fw'></i>
      weight: 1
      identifier: posts
      url: /posts/
    - name: Projects
      pre: <i class="fa fa-tasks fa-fw"></i>
      weight: 2
      identifier: projects
      url: /projects/
    - name: About
      pre: <i class='fa fa-user fa-fw'></i>
      weight: 3
      identifier: about
      url: /about/
    - name: Contact
      pre: <i class='fa fa-phone fa-fw'></i>
      weight: 4
      url: /contact/
    - name: Random Stuff
      pre: <i class='fa fa-random fa-fw'></i>
      weight: 5
